name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile || npm ci
      - name: Lint
        run: npm run lint
      - name: Format Check
        run: npx prettier --check "./src/**/*.+(js|ts|json)"
      - name: Test
        run: npm test
